services:
  - type: web
    name: cat-dog-classifier-api
    env: python
    rootDir: exercise_1/backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: MODEL_NAME
        value: mobilenet_v3_small
      - key: CHECKPOINT_PATH
        value: ../models_checkpoint/mobilenet_v3_small_head.pt
      - key: CORS_ORIGINS
        value: "*"
